### PR TITLE
Change import PropTypes from 'prop-types'

### PR DESCRIPTION
**Pull request by tomaskazatel**

### CODE REVIEW

**Comment by magrinj** [comment]
Hello, thanks for your MR, I'm actually looking for a way to change the import conditionally based on the `react-native` version. I don't have a lot of time for the moment to try something, so if you want to try something, go ahead :)

**Comment by tomaskazatel** [comment]
@magrinj In my opinion, it is not possible to set the record of dependencies based on the React version. Unfortunately, some package maintenance is always required.

Can you please merge this?

**Comment by magrinj** [comment]
Sorry for the delay, I will merge this

**Comment by magrinj** [comment]
It's released as version 1.1.0 :) Thanks!

**Pull request merged**
